'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const {setup,png}=require('./helpers/pilot-fixture.cjs');
const {createPilotArtifacts}=require('../gateway/pilot-artifacts.cjs');
const {createArtifactUpload}=require('../integrations/mcp/artifact-upload.cjs');
function env(t){const f=setup(t),task=f.task(),artifacts=createPilotArtifacts({store:f.store,root:f.root,now:f.now}),uploads=createArtifactUpload({store:f.store,artifacts,now:f.now}),spec={taskId:task.taskId,leaseId:task.leaseId,attempt:task.attempt,eventId:randomUUID(),contentType:'image/png'};return {f,task,artifacts,uploads,spec};}
test('MCP upload streams bounded chunks with stable duplicate acknowledgement',t=>{const {f,task,uploads,spec}=env(t),begin=uploads.begin(f.nodeId,spec),bytes=png();const call={uploadId:begin.uploadId,index:0,data:bytes.toString('base64')};assert.equal(uploads.chunk(f.nodeId,call).totalBytes,bytes.length);assert.equal(uploads.chunk(f.nodeId,call).totalBytes,bytes.length);const meta=uploads.finish(f.nodeId,{uploadId:begin.uploadId});assert.equal(meta.width,1);assert.equal(uploads.finish(f.nodeId,{uploadId:begin.uploadId}).artifactId,meta.artifactId);assert.equal(f.store.getPilotArtifact(meta.artifactId).taskId,task.taskId);});
test('MCP upload rejects bad encoding, order, conflict, cross-node and expiry',t=>{const {f,uploads,spec}=env(t),begin=uploads.begin(f.nodeId,spec);assert.throws(()=>uploads.chunk(f.nodeId,{uploadId:begin.uploadId,index:1,data:'YQ=='}));assert.throws(()=>uploads.chunk(f.nodeId,{uploadId:begin.uploadId,index:0,data:'YQ==garbage'}));uploads.chunk(f.nodeId,{uploadId:begin.uploadId,index:0,data:'YQ=='});assert.throws(()=>uploads.chunk(f.nodeId,{uploadId:begin.uploadId,index:0,data:'Yg=='}));assert.throws(()=>uploads.finish('other',{uploadId:begin.uploadId}));f.advance(90001);assert.throws(()=>uploads.finish(f.nodeId,{uploadId:begin.uploadId}));});
test('MCP chunks cannot bypass two MiB or survive cancellation and restart',t=>{const {f,task,artifacts,uploads,spec}=env(t),begin=uploads.begin(f.nodeId,spec),data=Buffer.alloc(65536,1).toString('base64');for(let index=0;index<32;index++)uploads.chunk(f.nodeId,{uploadId:begin.uploadId,index,data});assert.throws(()=>uploads.chunk(f.nodeId,{uploadId:begin.uploadId,index:32,data:'AQ=='}),/upload_too_large/);f.store.cancelTask(task.taskId);assert.throws(()=>uploads.finish(f.nodeId,{uploadId:begin.uploadId}));const restarted=createArtifactUpload({store:f.store,artifacts,now:f.now});assert.throws(()=>restarted.finish(f.nodeId,{uploadId:begin.uploadId}));assert.equal(f.store.listPilotArtifacts().length,0);});
