'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {randomBytes,createHmac}=require('node:crypto');
const {setup}=require('./helpers/pilot-fixture.cjs');
const {createPilotEvents}=require('../integrations/mcp/events.cjs');
function env(t,{badChallenge=false,status=200}={}){let fixtureCleanup;const f=setup({after:fn=>{fixtureCleanup=fn;}}),task=f.task(),key=randomBytes(32),principal={nodeId:f.nodeId},secret='whsec_'+Buffer.alloc(32).toString('base64'),params={name:'pilot.task_ready',arguments:{taskId:task.taskId},delivery:{mode:'webhook',url:'https://callback.example/dot',secret},ttlMs:300000},requests=[];const authorize=p=>{const n=f.store.getNode(p.nodeId);return !n.revoked&&!n.paused;};const transport=async(url,options)=>{const body=JSON.parse(options.body);requests.push({body,headers:options.headers});const timestamp=options.headers['webhook-timestamp'];const expected='v1,'+createHmac('sha256',Buffer.alloc(32)).update(options.headers['webhook-id']+'.'+timestamp+'.'+options.body).digest('base64');assert.equal(options.headers['webhook-signature'],expected);return new Response(JSON.stringify(body.type==='verification'?{challenge:badChallenge?'wrong':body.challenge}:{}),{status:body.type==='verification'?200:status});};const dbPath=path.join(f.dir,'events.db');let events=createPilotEvents({dbPath,encryptionKey:key,authorize,transport,now:f.now});t.after(()=>{try{events.close();}finally{key.fill(0);fixtureCleanup();}});return {f,task,key,principal,params,requests,dbPath,authorize,transport,get events(){return events;},reopen(){events.close();events=createPilotEvents({dbPath,encryptionKey:key,authorize,transport,now:f.now});},event:()=>({eventId:'evt_fixture',taskId:task.taskId,taskType:'browser.public_read',deadlineAt:task.deadlineAt})};}
test('events verify signed challenge, deduplicate and preserve encrypted subscriptions on restart',async t=>{const e=env(t),sub=await e.events.subscribe(e.principal,e.params);assert.equal(e.requests.length,1);const same=await e.events.subscribe(e.principal,e.params);assert.equal(same.id,sub.id);assert.equal(e.requests.length,1);e.events.publish(e.principal,e.event());e.events.publish(e.principal,e.event());e.reopen();assert.equal((await e.events.deliverDue()).delivered,1);assert.equal(e.f.store.getTask(e.task.taskId).status,'leased');assert.equal(e.requests.filter(x=>x.body.name==='pilot.task_ready').length,1);assert.equal(fs.readFileSync(e.dbPath).includes(Buffer.from(e.params.delivery.secret)),false);});
test('events reject invalid verification, secret and expanded filters',async t=>{const e=env(t,{badChallenge:true});await assert.rejects(e.events.subscribe(e.principal,e.params),/challenge_failed/);await assert.rejects(e.events.subscribe(e.principal,{...e.params,arguments:{taskId:e.task.taskId,nodeId:'other'}}));await assert.rejects(e.events.subscribe(e.principal,{...e.params,delivery:{...e.params.delivery,secret:'whsec_short'}}));});
test('events stop after cancellation, expiry or node revocation',async t=>{const e=env(t);await e.events.subscribe(e.principal,e.params);e.events.publish(e.principal,e.event());e.f.store.revokeNode(e.f.nodeId);assert.equal((await e.events.deliverDue()).delivered,0);assert.equal(e.requests.length,1);});
for(const status of [410,413])test('events do not retry terminal receiver '+status,async t=>{const e=env(t,{status});await e.events.subscribe(e.principal,e.params);e.events.publish(e.principal,e.event());assert.equal((await e.events.deliverDue()).delivered,0);e.f.advance(5000);await e.events.deliverDue();assert.equal(e.requests.length,2);});
test('events cap transient retries and unsubscribe idempotently',async t=>{const e=env(t,{status:503});await e.events.subscribe(e.principal,e.params);e.events.publish(e.principal,e.event());await e.events.deliverDue();e.f.advance(1000);await e.events.deliverDue();e.f.advance(2000);await e.events.deliverDue();e.f.advance(4000);await e.events.deliverDue();assert.equal(e.requests.length,4);const params={name:e.params.name,arguments:e.params.arguments,delivery:{mode:'webhook',url:e.params.delivery.url}};assert.equal(e.events.unsubscribe(e.principal,params).unsubscribed,true);assert.equal(e.events.unsubscribe(e.principal,params).unsubscribed,true);});
test('events reject wrong encryption key after reopening',async t=>{const e=env(t);await e.events.subscribe(e.principal,e.params);e.events.close();assert.throws(()=>createPilotEvents({dbPath:e.dbPath,encryptionKey:randomBytes(32),authorize:e.authorize,transport:e.transport,now:e.f.now}),/event_state_key_mismatch/);});
