'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {setup,png,output,result}=require('./helpers/pilot-fixture.cjs');
const {tls,listen}=require('./helpers/pilot-network.cjs');
const {createPilotArtifacts}=require('../gateway/pilot-artifacts.cjs');
const {createPilotNodeFacade}=require('../gateway/node-facade.cjs');
const {createMuseProxyTransport}=require('../sdk/transports/muse-proxy.cjs');
const {proxy}=require('./helpers/pilot-network.cjs');
async function env(t){const f=setup(t),a=createPilotArtifacts({store:f.store,root:f.root,now:f.now}),facade=createPilotNodeFacade({store:f.store,artifacts:a,tls,allowedNodeIds:[f.nodeId]});t.after(()=>facade.close());const origin=`https://127.0.0.1:${await listen(facade.server)}`,p=await proxy(t),fetch=createMuseProxyTransport({proxyUrl:p.url,targetOrigin:origin,ca:tls.cert});const call=(route,body,extra={})=>fetch(origin+route,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+f.token,'Content-Type':'application/json',...extra},body:body===undefined?undefined:JSON.stringify(body)});return {...f,f,facade,fetch,origin,call};}
test('facade exposes no admin, pairing, arbitrary paths or unauthenticated tasks',async t=>{const e=await env(t);assert.equal((await e.fetch(e.origin+'/health')).status,200);assert.equal((await e.fetch(e.origin+'/v1/manifest')).status,401);for(const route of ['/admin/v1/nodes','/v1/pair','/v1/%6danifest','/v1/manifest?token=x','/v1/manifest?foo=bar'])assert.equal((await e.call(route,{})).status,404);assert.equal((await e.call('/v1/manifest')).status,200);assert.equal((await e.call('/v1/manifest',undefined,{Origin:'https://example.com'})).status,403);assert.throws(()=>e.facade.server.listen(0,'0.0.0.0'));});
test('facade transports one scoped task, raw screenshot and validated result',async t=>{const e=await env(t);const queued=e.store.enqueueTask({targetNodeId:e.nodeId,scopeId:'public',taskType:'browser.public_read',input:{url:'https://example.com/',challenge:'A'.repeat(43)},deadlineAt:e.now()+300000});const task=await (await e.call('/v1/tasks/claim',{})).json();assert.equal(task.taskId,queued.taskId);const response=await e.fetch(e.origin+`/v1/pilot/tasks/${task.taskId}/artifact`,{method:'POST',headers:{Authorization:'Bearer '+e.token,'Content-Type':'image/png','X-Pilot-Lease-Id':task.leaseId,'X-Pilot-Attempt':String(task.attempt),'X-Pilot-Event-Id':'synthetic-upload'},body:png()});assert.equal(response.status,201);const artifact=await response.json(),ack=await (await e.call(`/v1/tasks/${task.taskId}/result`,result(task,output(artifact.artifactId)))).json();assert.equal(ack.accepted,true);assert.equal(e.store.getPilotAcceptance(task.taskId).state,'evidence_checked');assert.equal((await e.call('/v1/tasks/claim',{})).status,204);});
test('facade denies unapproved identity and expanded capabilities',async t=>{const e=await env(t),n=e.store.createNode({name:'expanded',capabilities:['browser.public_read','research.verify'],scopes:['public']});const token=e.store.pair(n.pairingCode).token;assert.equal((await e.call('/v1/manifest',undefined,{Authorization:'Bearer '+token})).status,403);assert.throws(()=>createPilotNodeFacade({store:e.store,artifacts:{},tls,allowedNodeIds:[]}));});
test('facade denies cancelled upload and mismatched task lease',async t=>{const e=await env(t),task=e.f.task();e.store.cancelTask(task.taskId);const response=await e.fetch(e.origin+`/v1/pilot/tasks/${task.taskId}/artifact`,{method:'POST',headers:{Authorization:'Bearer '+e.token,'Content-Type':'image/png','X-Pilot-Lease-Id':task.leaseId,'X-Pilot-Attempt':String(task.attempt),'X-Pilot-Event-Id':'cancelled-upload'},body:png()});assert.equal(response.status,409);assert.equal(e.store.listPilotArtifacts().length,0);});
