'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {randomUUID}=require('node:crypto');
const {createPilotArtifacts}=require('../gateway/pilot-artifacts.cjs');
const {setup,png,result}=require('./helpers/pilot-fixture.cjs');
function put(a,f,task,bytes=png(),eventId=randomUUID()){return a.put(f.nodeId,task,{eventId,contentType:'image/png',bytes});}
test('artifacts save and recover matching bounded PNG with idempotence',t=>{const f=setup(t),task=f.task();let a=createPilotArtifacts({store:f.store,root:f.root,now:f.now});const bytes=png(),eventId=randomUUID(),meta=put(a,f,task,bytes,eventId);assert.equal(meta.width,1);assert.equal(meta.height,1);assert.equal(meta.sizeBytes,bytes.length);assert.equal(put(a,f,task,bytes,eventId).artifactId,meta.artifactId);assert.deepEqual(a.get(f.nodeId,task.taskId,meta.artifactId).bytes,bytes);assert.throws(()=>put(a,f,task,png({padding:12}),eventId));assert.throws(()=>put(a,f,task));f.reopen();a=createPilotArtifacts({store:f.store,root:f.root,now:f.now});assert.deepEqual(a.get(f.nodeId,task.taskId,meta.artifactId).bytes,bytes);});
test('artifacts reject oversize, bad CRC, truncation, oversized dimensions and SVG',t=>{const f=setup(t),task=f.task(),a=createPilotArtifacts({store:f.store,root:f.root,now:f.now});const corrupt=png();corrupt[corrupt.length-1]^=1;for(const bytes of [Buffer.alloc(2*1024*1024+1),png().subarray(0,30),corrupt,png({width:4097}),Buffer.from('<svg/>')])assert.throws(()=>put(a,f,task,bytes));assert.throws(()=>a.put(f.nodeId,task,{eventId:randomUUID(),contentType:'image/svg+xml',bytes:png()}));assert.deepEqual(fs.readdirSync(f.root),[]);});
test('artifacts reject fake JPEG with truncated segments',t=>{const f=setup(t),task=f.task(),a=createPilotArtifacts({store:f.store,root:f.root,now:f.now});assert.throws(()=>a.put(f.nodeId,task,{eventId:randomUUID(),contentType:'image/jpeg',bytes:Buffer.from('ffd8ffc00011ffd9','hex')}));});
test('artifacts accept an actual JPEG encoder fixture and reject missing EOI',t=>{const f=setup(t),task=f.task(),a=createPilotArtifacts({store:f.store,root:f.root,now:f.now});
 const bytes=Buffer.from('/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAABAAEDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD9U6KKKAP/2Q==','base64');
 assert.throws(()=>a.put(f.nodeId,task,{eventId:randomUUID(),contentType:'image/jpeg',bytes:bytes.subarray(0,bytes.length-2)}));const meta=a.put(f.nodeId,task,{eventId:randomUUID(),contentType:'image/jpeg',bytes});assert.equal(meta.width,1);assert.equal(meta.height,1);assert.deepEqual(a.get(f.nodeId,task.taskId,meta.artifactId).bytes,bytes);
});
for(const boundary of ['cancel','revoke','expire'])test('artifacts deny '+boundary+' before writing',t=>{const f=setup(t),task=f.task(),a=createPilotArtifacts({store:f.store,root:f.root,now:f.now});if(boundary==='cancel')f.store.cancelTask(task.taskId);if(boundary==='revoke')f.store.revokeNode(f.nodeId);if(boundary==='expire')f.advance(90001);assert.throws(()=>put(a,f,task));assert.deepEqual(fs.readdirSync(f.root),[]);});
test('artifacts deny cross-node and caller-controlled paths',t=>{const f=setup(t),task=f.task(),a=createPilotArtifacts({store:f.store,root:f.root,now:f.now}),meta=put(a,f,task);const n=f.store.createNode({name:'other',capabilities:['browser.public_read'],scopes:['public']});assert.throws(()=>a.get(n.id,task.taskId,meta.artifactId));assert.throws(()=>a.get(f.nodeId,task.taskId,'../../pilot.db'));assert.throws(()=>a.put(f.nodeId,task,{eventId:randomUUID(),contentType:'image/png',bytes:png(),path:'../../escape'}));});
test('artifacts reject linked root and handle failed writes without metadata',t=>{const f=setup(t),task=f.task();const target=path.join(f.dir,'target');fs.mkdirSync(target);const link=path.join(f.dir,'link');fs.symlinkSync(target,link,process.platform==='win32'?'junction':'dir');assert.throws(()=>createPilotArtifacts({store:f.store,root:link,now:f.now}));const a=createPilotArtifacts({store:f.store,root:f.root,now:f.now});fs.rmdirSync(f.root);fs.writeFileSync(f.root,'blocked');assert.throws(()=>put(a,f,task));assert.equal(f.store.listPilotArtifacts().length,0);});
test('artifact storage caps total bytes and removes expired terminal evidence',t=>{const f=setup(t),a=createPilotArtifacts({store:f.store,root:f.root,now:f.now}),bytes=png({padding:2097000});for(let i=0;i<10;i++){const task=f.task();put(a,f,task,bytes);f.store.submitResult(f.nodeId,result(task,{error:'synthetic_failure'},'failed'));}const task=f.task();assert.throws(()=>put(a,f,task,bytes),/artifact_capacity/);assert.equal(f.store.listPilotArtifacts().length,10);f.advance(7*86400000+1);assert.equal(a.removeExpired(),10);assert.equal(f.store.listPilotArtifacts().length,0);assert.equal(fs.readdirSync(f.root).length,0);});
